// File generated by FlutterFire CLI.
// ignore_for_file: typ
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrpOJu6UOoI1CchrOdqSq3vljFZ63fTXM',
    appId: '1:27943857074:web:433f755ab5f0209b1ed2ab',
    messagingSenderId: '27943857074',
    projectId: 'makeup-mystery-app',
    authDomain: 'makeup-mystery-app.firebaseapp.com',
    storageBucket: 'makeup-mystery-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmwo42yUYKet8GhAbwtpjQCac7CxW2TnI',
    appId: '1:27943857074:android:d34643e2da21b9f01ed2ab',
    messagingSenderId: '27943857074',
    projectId: 'makeup-mystery-app',
    storageBucket: 'makeup-mystery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7s0Vx-y7vdsiXS294-2ZSPXUfzp8dto',
    appId: '1:27943857074:ios:4da831196e35c86b1ed2ab',
    messagingSenderId: '27943857074',
    projectId: 'makeup-mystery-app',
    storageBucket: 'makeup-mystery-app.firebasestorage.app',
    iosBundleId: 'com.makeupmystery.india',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7s0Vx-y7vdsiXS294-2ZSPXUfzp8dto',
    appId: '1:27943857074:ios:4da831196e35c86b1ed2ab',
    messagingSenderId: '27943857074',
    projectId: 'makeup-mystery-app',
    storageBucket: 'makeup-mystery-app.firebasestorage.app',
    iosBundleId: 'com.example.lumiere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrpOJu6UOoI1CchrOdqSq3vljFZ63fTXM',
    appId: '1:27943857074:web:a790c63a56fc41d01ed2ab',
    messagingSenderId: '27943857074',
    projectId: 'makeup-mystery-app',
    authDomain: 'makeup-mystery-app.firebaseapp.com',
    storageBucket: 'makeup-mystery-app.firebasestorage.app',
  );

}